# Generated by Django 6.1.1 on 2026-09-25 03:13

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_unique_ci', violation_error_message='A category with this name already exists.')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('source', models.CharField(help_text='Where the article came from, e.g. "Reuters".', max_length=100)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news.category')),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-date_and_time', '-id'],
                'indexes': [models.Index(fields=['-date_and_time'], name='news_date_time_idx')],
            },
        ),
    ]
